---
version: "2.1"
services:
  ubuntu-mirror:
    image: ubuntu-mirror
    container_name: ubuntu-mirror
    volumes:
      - /volume1/docker/ubuntu-mirror/data:/var/data/ubuntu
    ports:
      - 80:80
    restart: unless-stopped
    # if direct exists
    networks:
      direct_network:
        ipv4_address: 192.168.0.248
networks:
  direct_network:
    external: true
# if direct doesn't exist
# networks:
#   netbootxyz_network:
#    ipv4_address: 192.168.0.250
# networks:
#   netbootxyz_network:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24
#           gateway: 192.168.0.1
#           ip_range: 192.168.0.250/32
